# Generated by Django 4.2.5 on 2023-10-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benutzer',
            name='_role',
            field=models.SmallIntegerField(default=0),
        ),
    ]
