# Generated by Django 4.2.5 on 2023-10-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benutzer',
            options={'managed': True},
        ),
    ]
