# Generated by Django 4.2.5 on 2023-10-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_benutzer_groups_benutzer_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benutzer',
            options={'managed': False},
        ),
    ]
