# Generated by Django 4.2.5 on 2023-11-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_modul_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kommentar',
        ),
    ]
