# Generated by Django 4.2.5 on 2023-11-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_delete_kommentar'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'StudyArea',
                'managed': False,
            },
        ),
    ]
